steps:
# 1：イメージを作成
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/sample:$COMMIT_SHA', '-f', 'app/Dockerfile', '.', '--build-arg', 'HOST=${_HOST}', '--build-arg', 'USER=${_USER}', '--build-arg', 'PASSWORD=${_PASSWORD}', '--build-arg', 'DATABASE=${_DATABASE}', '--build-arg', 'PORT=${_PORT}']
images: ['gcr.io/$PROJECT_ID/sample:$COMMIT_SHA']

